---
- name: Deploy Node.js App to EC2
  hosts: node_app
  become: yes
  gather_facts: false

  tasks:
    - name: Update APT cache with retries
      apt:
        update_cache: yes
      retries: 3
      delay: 5
      register: result
      until: result is succeeded

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Clone Node.js app from GitHub
      git:
        repo: https://github.com/pranjalls/DevOps-NodeApp-Project.git
        dest: /home/ubuntu/app
        version: main
        force: yes

    - name: Install Node.js dependencies
      npm:
        path: /home/ubuntu/app

    - name: Kill any running node processes (cleanup)
      shell: pkill -f index.js || true
      ignore_errors: yes

    - name: Run app in background using nohup
      shell: |
        nohup node /home/ubuntu/app/src/index.js > /home/ubuntu/app/app.log 2>&1 &
      args:
        executable: /bin/bash
