---
- name: Deploy Node.js App via Docker
  hosts: web
  become: yes
  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from Docker Hub
      shell: docker pull ppranshinn0225/devops-node-app:latest

    - name: Run Docker container (map port 80 → 3000)
      shell: |
        docker stop nodeapp || true
        docker rm nodeapp || true
        docker run -d --name nodeapp -p 80:3000 ppranshinn0225/devops-node-app:latest
